### list
GET http://localhost:9129/list?app=app1&env=dev&ns=public

### version
GET http://localhost:9129/version?app=app1&env=dev&ns=public

### update
POST http://localhost:9129/update?app=app1&env=dev&ns=public
Content-Type: application/json

{
  "zw.a": "deva3000",
  "zw.b": "devb3000",
  "zw.c": "cc2000",
  "zw.d": "dd2000"
}

### version
GET http://localhost:9129/version?app=app1&env=dev&ns=public

### demo 9130
GET http://localhost:9130/demo