server:
    port: 9129

spring:
    application:
        name: zwconfig-server
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/zwconfig
      username: root
      password: Zw@03507323633

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: info
    org.springframework: info
