server:
  port: 9129

spring:
  application:
    name: zwconfig-server
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:h2db
    username: root
    password: 123456
  sql:
    init:
      schema-locations: classpath:db.sql
      mode: always

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: info
    org.springframework: info
