### list
GET http://localhost:9129/list?app=app1&env=dev&ns=public

### update
POST http://localhost:9129/update?app=app1&env=dev&ns=public
Content-Type: application/json

{
  "zw.a": "dev200",
  "zw.c": "cc200",
  "zw.d": "dd200"
}